In [1]:
# Importing libraries
# -------------------
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
# ---------------------
dataset = pd.read_csv("Multiple-Linear-Dataset.csv")
dataset.head()

Product_1  Product_2  Product_3 Location     Profit
0  165349.20  136897.80  471784.10   City_1  192261.83
1  162597.70  151377.59  443898.53   City_2  191792.06
2  153441.51  101145.55  407934.54   City_3  191050.39
3  144372.41  118671.85  383199.62   City_1  182901.99
4  142107.34   91391.77  366168.42   City_3  166187.94

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values
X

array([[165349.2, 136897.8, 471784.1, 'City_1'],
       [162597.7, 151377.59, 443898.53, 'City_2'],
       [153441.51, 101145.55, 407934.54, 'City_3'],
       [144372.41, 118671.85, 383199.62, 'City_1'],
       [142107.34, 91391.77, 366168.42, 'City_3'],
       [131876.9, 99814.71, 362861.36, 'City_1'],
       [134615.46, 147198.87, 127716.82, 'City_2'],
       [130298.13, 145530.06, 323876.68, 'City_3'],
       [120542.52, 148718.95, 311613.29, 'City_1'],
       [123334.88, 108679.17, 304981.62, 'City_2'],
       [101913.08, 110594.11, 229160.95, 'City_3'],
       [100671.96, 91790.61, 249744.55, 'City_2'],
       [93863.75, 127320.38, 249839.44, 'City_3'],
       [91992.39, 135495.07, 252664.93, 'City_2'],
       [119943.24, 156547.42, 256512.92, 'City_3'],
       [114523.61, 122616.84, 261776.23, 'City_1'],
       [78013.11, 121597.55, 264346.06, 'City_2'],
       [94657.16, 145077.58, 282574.31, 'City_1'],
       [91749.16, 114175.79, 294919.57, 'City_3'],
       [86419.7, 153514.1

In [4]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [5]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
print(X)

[[165349.2 136897.8 471784.1 0]
 [162597.7 151377.59 443898.53 1]
 [153441.51 101145.55 407934.54 2]
 [144372.41 118671.85 383199.62 0]
 [142107.34 91391.77 366168.42 2]
 [131876.9 99814.71 362861.36 0]
 [134615.46 147198.87 127716.82 1]
 [130298.13 145530.06 323876.68 2]
 [120542.52 148718.95 311613.29 0]
 [123334.88 108679.17 304981.62 1]
 [101913.08 110594.11 229160.95 2]
 [100671.96 91790.61 249744.55 1]
 [93863.75 127320.38 249839.44 2]
 [91992.39 135495.07 252664.93 1]
 [119943.24 156547.42 256512.92 2]
 [114523.61 122616.84 261776.23 0]
 [78013.11 121597.55 264346.06 1]
 [94657.16 145077.58 282574.31 0]
 [91749.16 114175.79 294919.57 2]
 [86419.7 153514.11 0.0 0]
 [76253.86 113867.3 298664.47 1]
 [78389.47 153773.43 299737.29 0]
 [73994.56 122782.75 303319.26 2]
 [67532.53 105751.03 304768.73 2]
 [77044.01 99281.34 140574.81 0]
 [64664.71 139553.16 137962.62 1]
 [75328.87 144135.98 134050.07 2]
 [72107.6 127864.55 353183.81 0]
 [66051.52 182645.56 118148.2 2]
 [65605.48 153032.0

In [6]:
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(X).toarray()
print(X)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 1. 0.]]


In [7]:
# Avoiding the Dummy Variable Trap
X = X[:, 1:]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [10]:
y_pred = regressor.predict(X_test)

In [11]:
# Building the optimal model using Backward Elimination
import statsmodels.api as sm
X = np.append(arr=np.ones((50, 1)).astype(int), values=X, axis=1)
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()
X_opt = X[:, [0, 1, 3, 4, 5]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()
X_opt = X[:, [0, 3, 4, 5]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()
X_opt = X[:, [0, 3, 5]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()
X_opt = X[:, [0, 3]]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.050
Model:                            OLS   Adj. R-squared:                  0.030
Method:                 Least Squares   F-statistic:                     2.532
Date:                Wed, 14 Jun 2023   Prob (F-statistic):              0.118
Time:                        15:49:01   Log-Likelihood:                -599.37
No. Observations:                  50   AIC:                             1203.
Df Residuals:                      48   BIC:                             1207.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.133e+05   5670.069     19.980      0.000    1.02e+05    1.25e+05
x1          -6.38e+04   4.01e+04     -1.591      0.118   -1.44e+05    1.68e+04
==============================================================================
Omnibus:                        0.164   Durbin-Watson:                   0.114
Prob(Omnibus):                  0.921   Jarque-Bera (JB):                0.001
Skew:                           0.009   Prob(JB):                         1.00
Kurtosis:                       2.989   Cond. No.                         7.15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""